[package]
name = "generator"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
good_lp = "1.14.0"
indicatif = "0.17.11"
rand = "0.9.1"
rand_chacha = "0.9.0"
ron = "0.10.1"
serde = { version = "1.0.219", features = ["derive"] }
